# Generated by Django 2.2.24 on 2021-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211019_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
