# Generated by Django 2.2.24 on 2021-10-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
