# Generated by Django 2.2.24 on 2021-10-25 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consulta',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
