# Generated by Django 2.2.24 on 2021-10-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211025_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='fecha',
        ),
    ]
